<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="G-0439" name="validateCollege_InformationSRM.ValidateCollege_InformationSRM" tests="6" failures="0" timestamp="4 May 2016 07:42:29 GMT" time="0.007" errors="6">
  <testcase name="SRM__Lead_Details" time="0.000" classname="validateCollege_InformationSRM.ValidateCollege_InformationSRM">
    <error type="java.lang.Throwable" message="Method ValidateCollege_InformationSRM.SRM__Lead_Details(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateCollege_InformationSRM@1b4de03] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ValidateCollege_InformationSRM.SRM__Lead_Details(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateCollege_InformationSRM@1b4de03] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1052)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- SRM__Lead_Details -->
  <testcase name="Lead_Flow" time="0.000" classname="validateCollege_InformationSRM.ValidateCollege_InformationSRM">
    <error type="java.lang.Throwable" message="Method ValidateCollege_InformationSRM.Lead_Flow(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateCollege_InformationSRM@1b4de03] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ValidateCollege_InformationSRM.Lead_Flow(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateCollege_InformationSRM@1b4de03] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1052)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Lead_Flow -->
  <testcase name="VerifyLeadInSRM" time="0.000" classname="validateCollege_InformationSRM.ValidateCollege_InformationSRM">
    <error type="java.lang.Throwable" message="Method ValidateCollege_InformationSRM.VerifyLeadInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateCollege_InformationSRM@1b4de03] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ValidateCollege_InformationSRM.VerifyLeadInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateCollege_InformationSRM@1b4de03] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1052)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- VerifyLeadInSRM -->
  <testcase name="VerifyNewOpportunityInSRM" time="0.000" classname="validateCollege_InformationSRM.ValidateCollege_InformationSRM">
    <error type="java.lang.Throwable" message="Method ValidateCollege_InformationSRM.VerifyNewOpportunityInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateCollege_InformationSRM@1b4de03] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ValidateCollege_InformationSRM.VerifyNewOpportunityInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateCollege_InformationSRM@1b4de03] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1052)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- VerifyNewOpportunityInSRM -->
  <testcase name="VerifyOpportunityInSRM" time="0.000" classname="validateCollege_InformationSRM.ValidateCollege_InformationSRM">
    <error type="java.lang.Throwable" message="Method ValidateCollege_InformationSRM.VerifyOpportunityInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateCollege_InformationSRM@1b4de03] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ValidateCollege_InformationSRM.VerifyOpportunityInSRM(java.lang.reflect.Method)[pri:0, instance:validateCollege_InformationSRM.ValidateCollege_InformationSRM@1b4de03] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1052)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- VerifyOpportunityInSRM -->
  <testcase name="BrowseToAddInfoCallLeadPage" time="0.007" classname="validateCollege_InformationSRM.ValidateCollege_InformationSRM">
    <error type="org.testng.TestNGException" message="
Parameter &#039;Browser&#039; is required by @Configuration on method BeforeNavigation but has not been marked @Optional or defined
in C:\Users\ravinder.kumar\AppData\Local\Temp\testng-eclipse--1880513344\testng-customsuite.xml">
      <![CDATA[org.testng.TestNGException: 
Parameter 'Browser' is required by @Configuration on method BeforeNavigation but has not been marked @Optional or defined
in C:\Users\ravinder.kumar\AppData\Local\Temp\testng-eclipse--1880513344\testng-customsuite.xml
	at org.testng.internal.Parameters.createParameters(Parameters.java:148)
	at org.testng.internal.Parameters.createParameters(Parameters.java:361)
	at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:84)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:199)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- BrowseToAddInfoCallLeadPage -->
</testsuite> <!-- validateCollege_InformationSRM.ValidateCollege_InformationSRM -->
